[package]
name = "WASM_image_style_transfer"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Window","Document"] }
gloo-console = "0.3"
js-sys = "0.3"